[licenses]
allow = [
    "MIT",
    "Apache-2.0",
    "BSD-3-Clause",
    "Unicode-DFS-2016"
]

[bans]
multiple-versions = "warn"
wildcards = "deny"

skip = [
    { crate = "sync_wrapper@0.1.2", reason = "pending tower PR #788" },
    { crate = "tower@0.4.13", reason = "pending hyper-util PR #144" },
    { crate = "windows-sys", reason = "this crate is never up to date" },
]

[sources]
unknown-registry = "deny"
unknown-git = "deny"
